# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
wheels/
share/python-wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
.deploy-env/

# Mac file
.DS_Store

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/

# Git
.git/
.gitignore
.pre-commit-config.yaml

# Docker
.dockerignore
Dockerfile

# FFModel repo files
docs/
azure-pipelines.yml

# .ffmodel config files
.ffmodel*
